import Head from "next/head";
// Local | React-Redux
function Home() {
  return (
    <>
      <Head>
        <title>Digitale Deluxe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="section section--home fp-auto-height-responsive">
        {/* <Home data={displayedData.home} /> */}
        bh
      </section>
      {/* <section className="section section--skills fp-auto-height-responsive">
        <Skills data={displayedData.skills} />
      </section>
      <section className="section section--projects fp-auto-height-responsive" ref={projectRef}>
        {projectInView && <Projects data={displayedData.projects} />}
      </section>
      <section className="section section--contact fp-auto-height-responsive" ref={contactRef}>
        {contactInView && <Contact data={displayedData.contact} />}
      </section>
      <section className="section fp-auto-height footer">
        <Footer data={displayedData.footer} />
      </section> */}
    </>
  );
}

export default Home;
